'use client';

import { useState } from 'react';
import { useLocale } from 'next-intl';
import type { ApiApp } from '@/lib/apigee';

const T_EN = {
  productSection: 'API Product Defaults',
  productSubtitle: 'Shared limit for all apps; applies when no override is set. Takes effect ~5 min after change (Apigee attribute cache TTL).',
  thProduct: 'Product', thReqQuota: 'Request Quota', thTokenQuota: 'Token Quota', thTimeWindow: 'Time Window', thActions: 'Actions',
  productProd: 'llm-gateway-product (production)',
  perMin: 'per minute', perHour: 'per hour', perDay: 'per day',
  reqMin: 'req/min', tokensValid: 'effective tokens',
  appSection: 'Per-App Quota',
  appSubtitlePrefix: 'Override product default for fine-grained per-client control. Empty means inherit product default.',
  priorityLine: 'Priority: ',
  appOverrideTag: 'App override',
  productDefaultTag: 'Product default',
  policyFallback: ' > Product default > Policy fallback (1M tokens/hr)',
  thAppDev: 'App / Developer',
  thSource: 'Source',
  thHourUsage: 'Usage This Hour',
  thOverride: 'Token Quota Override (/hr)',
  noAppData: 'No app data',
  inputPlaceholder: 'Empty = use Product default',
  clearTitle: 'Clear override, fall back to Product default',
  clearBtn: '✕ Clear',
  appLevelNote: '⚙ App-level overrides write to Apigee app custom attribute ',
  appLevelSuffix: ', read by JS-ResolveTokenQuota in the proxy with priority over product default.',
  weightTitle: 'Model Cost Weights',
  weightDescL1: 'effective tokens = (input + output × 4) × weight. Baseline: gemini-2.0-flash-001 = 1.0',
  weightDescL2: ' applies only to billable models (Vertex AI). Free models (OpenCode) are excluded by the proxy and unaffected.',
  autoGenerateLink: 'Auto-generate',
  generatedBy: (model: string) => `✓ Auto-generated by ${model} based on latest Vertex AI pricing`,
  generateFailed: 'Generation failed',
  generating: 'Generating...',
  autoGenerateBtn: '⚡ Auto-generate weights',
  billableModelsHeader: 'Billable models (Vertex AI · subject to Token Quota)',
  thModel: 'Model',
  thWeight: 'Weight',
  freeModelsHeader: 'Free models (OpenCode Zen · not subject to Token Quota)',
  thStatus: 'Status',
  noQuotaTag: 'no quota',
  weightsRedeployNote: '⚠ After modification, sync compute-effective-tokens.js and redeploy the proxy',
  saving: 'Saving...',
  saved: '✓ Saved',
  save: 'Save',
  errSaveFailed: 'Save failed',
};

const T_ZH = {
  productSection: 'API Product 默认配额',
  productSubtitle: '所有 App 共用的上限，未单独设置覆盖时生效。修改后约 5 分钟生效（Apigee 属性缓存 TTL）。',
  thProduct: 'Product', thReqQuota: '请求配额', thTokenQuota: 'Token 配额', thTimeWindow: '时间窗口', thActions: '操作',
  productProd: 'llm-gateway-product（生产）',
  perMin: '每分钟', perHour: '每小时', perDay: '每天',
  reqMin: 'req/min', tokensValid: '有效 tokens',
  appSection: '按 App 独立配额',
  appSubtitlePrefix: '覆盖 Product 默认值，精细控制每个客户端的用量。留空表示沿用 Product 默认配额。',
  priorityLine: '优先级：',
  appOverrideTag: 'App 覆盖',
  productDefaultTag: 'Product 默认',
  policyFallback: ' > Product 默认 > Policy 兜底（1M tokens/hr）',
  thAppDev: 'App / 开发者',
  thSource: '来源',
  thHourUsage: '本小时用量',
  thOverride: 'Token 配额覆盖（/hr）',
  noAppData: '暂无 App 数据',
  inputPlaceholder: '留空 = 使用 Product 默认',
  clearTitle: '清除覆盖，回退到 Product 默认',
  clearBtn: '✕ 清除',
  appLevelNote: '⚙ App 级覆盖写入 Apigee App 自定义属性 ',
  appLevelSuffix: '，由代理中 JS-ResolveTokenQuota 读取并优先使用。',
  weightTitle: '模型成本权重',
  weightDescL1: '有效 tokens = (输入 + 输出 × 4) × 权重。基准：gemini-2.0-flash-001 = 1.0',
  weightDescL2: ' 仅针对计费模型（Vertex AI）。免费模型（OpenCode）由代理层排除，不受权重影响。',
  autoGenerateLink: '自动生成',
  generatedBy: (model: string) => `✓ 由 ${model} 根据最新 Vertex AI 定价自动生成`,
  generateFailed: '生成失败',
  generating: '生成中…',
  autoGenerateBtn: '⚡ 自动生成权重',
  billableModelsHeader: '计费模型（Vertex AI · 受 Token Quota 约束）',
  thModel: '模型',
  thWeight: '权重系数',
  freeModelsHeader: '免费模型（OpenCode Zen · 不受 Token Quota 约束）',
  thStatus: '状态',
  noQuotaTag: '不计配额',
  weightsRedeployNote: '⚠ 修改后需同步更新 apigee/proxies/llm-gateway/apiproxy/resources/jsc/compute-effective-tokens.js 并重新部署',
  saving: '保存中…',
  saved: '✓ 已保存',
  save: '保存',
  errSaveFailed: '保存失败',
};

// Default model cost weights (baseline = gemini-2.5-flash-lite at 1.0x).
// Updated 2026-04: dropped retired Gemini 2.0 series; added Claude 4.7 Opus and Grok 4.20 reasoning.
const INITIAL_WEIGHTS: Record<string, number> = {
  // Gemini 2.5
  'gemini-2.5-flash-lite':  1.0,
  'gemini-2.5-flash':       8.75,
  'gemini-2.5-pro':         37.5,
  'gemini-2.5-flash-image': 7.5,
  // Gemini 3.x
  'gemini-3-flash-preview':       8.75,
  'gemini-3.1-flash-lite-preview':2.5,
  'gemini-3.1-pro-preview':       37.5,
  'gemini-3.1-flash-image-preview': 12.5,
  // Claude
  'claude-haiku-4-5':       3.125,
  'claude-sonnet-4-5':      37.5,
  'claude-sonnet-4-6':      37.5,
  'claude-opus-4-5':        187.5,
  'claude-opus-4-6':        187.5,
  'claude-opus-4-7':        187.5,
  // MaaS partners
  'deepseek-v3.2':          2.75,
  'kimi-k2-thinking':       6.25,
  'minimax-m2':             4.0,
  'qwen3-235b':             5.0,
  // xAI Grok
  'grok-4.20-reasoning':    30.0,
};

const FREE_MODELS = [
  { name: 'opencode/nemotron-3-super-free',     provider: 'Nvidia / OpenCode Zen'  },
  { name: 'opencode/big-pickle',                provider: 'Stealth / OpenCode Zen' },
  { name: 'opencode/minimax-m2.5-free',         provider: 'MiniMax / OpenCode Zen' },
  { name: 'opencode/hy3-preview-free',          provider: 'Hy3 / OpenCode Zen'     },
  { name: 'opencode/ling-2.6-flash-free',       provider: 'InclusionAI / OpenCode Zen' },
  { name: 'opencode/gpt-5-nano',                provider: 'OpenAI / OpenCode Zen'  },
];

const PRODUCTS = [
  { name: 'llm-gateway-product', reqQuota: 1000, tokenQuota: 1_000_000, interval: '1', timeUnit: 'hour' },
];

const LABEL_STYLE = {
  fontFamily: 'IBM Plex Mono, monospace',
  fontSize: '9px',
  letterSpacing: '0.18em',
  textTransform: 'uppercase' as const,
  color: 'var(--c-txt-3)',
};

function getAppQuotaOverride(app: ApiApp): string {
  return app.attributes?.find(a => a.name === 'token.quota.limit')?.value ?? '';
}

interface ProductConfig {
  reqQuota:   number;
  tokenQuota: number;
  interval:   string;
  timeUnit:   string;
}

interface QuotaEditorProps {
  apps:                ApiApp[];
  tokenUsage?:         Record<string, number>;
  initialProductConfig?: ProductConfig;
}

export function QuotaEditor({ apps, tokenUsage = {}, initialProductConfig }: QuotaEditorProps) {
  const locale = useLocale();
  const T = locale === 'zh' ? T_ZH : T_EN;

  const [weights, setWeights]   = useState(INITIAL_WEIGHTS);
  const [products, setProducts] = useState(() =>
    PRODUCTS.map(p => initialProductConfig ? { ...p, ...initialProductConfig } : p)
  );

  const [prodSaving, setProdSaving] = useState<string | null>(null);
  const [prodSaved,  setProdSaved]  = useState<string | null>(null);

  const [appLimits, setAppLimits] = useState<Record<string, string>>(
    Object.fromEntries(apps.map(a => [a.appId, getAppQuotaOverride(a)]))
  );
  const [appSaving, setAppSaving] = useState<string | null>(null);
  const [appSaved,  setAppSaved]  = useState<string | null>(null);
  const [appError,  setAppError]  = useState<string | null>(null);

  async function saveProductQuota(p: typeof PRODUCTS[number]) {
    setProdSaving(p.name);
    try {
      const res = await fetch('/api/quota', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          productName:     p.name,
          tokenQuotaLimit: p.tokenQuota,
          reqQuota:        p.reqQuota,
          interval:        p.interval,
          timeUnit:        p.timeUnit,
        }),
      });
      if (res.ok) {
        setProdSaved(p.name);
        setTimeout(() => setProdSaved(null), 2000);
      }
    } catch { /* swallow */ }
    finally { setProdSaving(null); }
  }

  async function saveAppQuota(app: ApiApp) {
    if (!app.developerEmail) return;
    setAppSaving(app.appId);
    setAppError(null);
    try {
      const limit = appLimits[app.appId];
      const res = await fetch('/api/quota/app', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          developerEmail: app.developerEmail,
          appName: app.name,
          tokenQuotaLimit: limit === '' ? null : Number(limit),
        }),
      });
      if (!res.ok) {
        const d = await res.json();
        setAppError(d.error ?? T.errSaveFailed);
      } else {
        setAppSaved(app.appId);
        setTimeout(() => setAppSaved(null), 2000);
      }
    } catch (e) { setAppError(String(e)); }
    finally { setAppSaving(null); }
  }

  return (
    <div className="space-y-4">

      <Section title={T.productSection} subtitle={T.productSubtitle}>
        <table className="w-full">
          <thead>
            <tr style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
              {[T.thProduct, T.thReqQuota, T.thTokenQuota, T.thTimeWindow, T.thActions].map(h => (
                <th key={h} className="px-5 py-3 text-left" style={LABEL_STYLE}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {products.map(p => (
              <tr key={p.name} style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
                <td className="px-5 py-4">
                  <div className="text-[12px] font-medium" style={{ color: 'var(--c-txt-1)' }}>{T.productProd}</div>
                </td>
                <td className="px-5 py-4">
                  <NumInput
                    value={p.reqQuota}
                    onChange={v => setProducts(prev => prev.map(x => x.name === p.name ? { ...x, reqQuota: v } : x))}
                    unit={T.reqMin}
                    width="w-24"
                  />
                </td>
                <td className="px-5 py-4">
                  <NumInput
                    value={p.tokenQuota}
                    onChange={v => setProducts(prev => prev.map(x => x.name === p.name ? { ...x, tokenQuota: v } : x))}
                    unit={T.tokensValid}
                    width="w-32"
                  />
                </td>
                <td className="px-5 py-4">
                  <select
                    value={`${p.interval}_${p.timeUnit}`}
                    onChange={e => {
                      const [interval, timeUnit] = e.target.value.split('_');
                      setProducts(prev => prev.map(x => x.name === p.name ? { ...x, interval, timeUnit } : x));
                    }}
                    className="text-[11px] px-2 py-1.5 rounded-sm outline-none"
                    style={{ fontFamily: 'IBM Plex Mono, monospace', background: 'var(--c-bg)', border: '1px solid var(--c-border)', color: 'var(--c-txt-1)' }}
                  >
                    <option value="1_minute">{T.perMin}</option>
                    <option value="1_hour">{T.perHour}</option>
                    <option value="1_day">{T.perDay}</option>
                  </select>
                </td>
                <td className="px-5 py-4">
                  <SaveBtn T={T}
                    saving={prodSaving === p.name}
                    saved={prodSaved === p.name}
                    onClick={() => saveProductQuota(p)}
                  />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </Section>

      <Section
        title={T.appSection}
        subtitle={
          <>
            {T.appSubtitlePrefix}
            <br />
            {T.priorityLine}<span style={{ color: 'var(--c-green)' }}>{T.appOverrideTag}</span>{T.policyFallback}
          </>
        }
      >
        {appError && (
          <div className="px-5 py-2 text-[11px]" style={{ color: 'var(--c-red)', fontFamily: 'IBM Plex Mono, monospace', background: 'rgba(244,63,94,0.08)', borderBottom: '1px solid var(--c-border-dim)' }}>
            ✗ {appError}
          </div>
        )}
        <table className="w-full">
          <thead>
            <tr style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
              {[T.thAppDev, T.thSource, T.thHourUsage, T.thOverride, T.thActions].map(h => (
                <th key={h} className="px-5 py-3 text-left" style={LABEL_STYLE}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {apps.map(app => {
              const override = appLimits[app.appId] ?? '';
              const hasOverride = override !== '';
              return (
                <tr key={app.appId} style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
                  <td className="px-5 py-3">
                    <div className="text-[12px] font-medium" style={{ color: 'var(--c-txt-1)' }}>{app.name}</div>
                    <div className="text-[10px] mt-0.5" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-3)' }}>
                      {app.developerEmail}
                    </div>
                  </td>

                  <td className="px-5 py-3">
                    <span
                      className="text-[9px] px-1.5 py-0.5 rounded-sm tracking-[0.08em] uppercase"
                      style={{
                        fontFamily: 'IBM Plex Mono, monospace',
                        color:      hasOverride ? 'var(--c-green)' : 'var(--c-txt-3)',
                        background: hasOverride ? 'rgba(0,232,122,0.08)' : 'transparent',
                        border:     hasOverride ? '1px solid rgba(0,232,122,0.2)' : '1px solid var(--c-border-dim)',
                      }}
                    >
                      {hasOverride ? T.appOverrideTag : T.productDefaultTag}
                    </span>
                  </td>

                  <td className="px-5 py-3" style={{ minWidth: '160px' }}>
                    {(() => {
                      const used  = tokenUsage[app.name] ?? 0;
                      const appOverride = app.attributes?.find(a => a.name === 'token.quota.limit')?.value;
                      const limit = Number(
                        (appOverride && Number(appOverride) > 0 ? appOverride : null) ??
                        initialProductConfig?.tokenQuota ??
                        1_000_000
                      );
                      const pct   = Math.min(used / limit, 1);
                      const barC  = pct > 0.9 ? 'var(--c-red)' : pct > 0.7 ? 'var(--c-amber)' : 'var(--c-green)';
                      const fmtN  = (n: number) => n >= 1_000_000 ? `${(n/1_000_000).toFixed(1)}M` : n >= 1_000 ? `${(n/1_000).toFixed(0)}K` : String(n);
                      return used > 0 ? (
                        <div>
                          <div className="flex items-center gap-2 mb-1">
                            <div className="flex-1 h-1 rounded-full" style={{ background: 'var(--c-border)' }}>
                              <div className="h-full rounded-full" style={{ width: `${pct * 100}%`, background: barC }} />
                            </div>
                            <span className="text-[10px] whitespace-nowrap" style={{ fontFamily: 'IBM Plex Mono, monospace', color: barC }}>
                              {Math.round(pct * 100)}%
                            </span>
                          </div>
                          <div className="text-[9px]" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-3)' }}>
                            {fmtN(used)} / {fmtN(limit)} tokens
                          </div>
                        </div>
                      ) : (
                        <span className="text-[10px]" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-3)' }}>—</span>
                      );
                    })()}
                  </td>

                  <td className="px-5 py-3">
                    <div className="flex items-center gap-2">
                      <input
                        type="number"
                        placeholder={T.inputPlaceholder}
                        value={override}
                        onChange={e => setAppLimits(prev => ({ ...prev, [app.appId]: e.target.value }))}
                        className="w-48 text-[11px] px-2 py-1.5 rounded-sm outline-none"
                        style={{
                          fontFamily: 'IBM Plex Mono, monospace',
                          background: 'var(--c-bg)',
                          border: '1px solid var(--c-border)',
                          color: hasOverride ? 'var(--c-green)' : 'var(--c-txt-2)',
                        }}
                      />
                      {hasOverride && (
                        <button
                          onClick={() => {
                            setAppLimits(prev => ({ ...prev, [app.appId]: '' }));
                          }}
                          className="text-[10px]"
                          style={{ color: 'var(--c-txt-3)', background: 'none', border: 'none', cursor: 'pointer', fontFamily: 'IBM Plex Mono, monospace' }}
                          title={T.clearTitle}
                        >
                          {T.clearBtn}
                        </button>
                      )}
                    </div>
                  </td>

                  <td className="px-5 py-3">
                    <SaveBtn T={T}
                      saving={appSaving === app.appId}
                      saved={appSaved === app.appId}
                      onClick={() => saveAppQuota(app)}
                    />
                  </td>
                </tr>
              );
            })}
            {apps.length === 0 && (
              <tr>
                <td colSpan={5} className="px-5 py-8 text-center text-[12px]" style={{ color: 'var(--c-txt-3)' }}>
                  {T.noAppData}
                </td>
              </tr>
            )}
          </tbody>
        </table>
        <div className="px-5 py-3 text-[10px]" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-3)', borderTop: '1px solid var(--c-border-dim)' }}>
          {T.appLevelNote}<code>token.quota.limit</code>{T.appLevelSuffix}
        </div>
      </Section>

      <WeightSection T={T} weights={weights} onWeightsChange={setWeights} />
    </div>
  );
}

function WeightSection({
  T, weights, onWeightsChange,
}: {
  T: typeof T_EN;
  weights: Record<string, number>;
  onWeightsChange: (w: Record<string, number>) => void;
}) {
  const [generating, setGenerating] = useState(false);
  const [genError,   setGenError]   = useState('');
  const [genModel,   setGenModel]   = useState('');

  async function autoGenerate() {
    setGenerating(true);
    setGenError('');
    setGenModel('');
    try {
      const res  = await fetch('/api/weights/generate', { method: 'POST' });
      const data = await res.json();
      if (!res.ok) { setGenError(data.error ?? T.generateFailed); return; }

      onWeightsChange({ ...weights, ...data.weights });
      setGenModel(data.model ?? '');
    } catch (e) {
      setGenError(String(e));
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="rounded-md overflow-hidden" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)' }}>
      <div className="flex items-start justify-between px-5 py-4" style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
        <div>
          <div className="text-[13px] font-semibold" style={{ fontFamily: 'Syne, sans-serif' }}>{T.weightTitle}</div>
          <div className="text-[11px] mt-1" style={{ color: 'var(--c-txt-3)' }}>
            {T.weightDescL1}<br />
            <span style={{ color: 'var(--c-blue)' }}>{T.autoGenerateLink}</span>{T.weightDescL2}
          </div>
          {genModel && (
            <div className="text-[10px] mt-1" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-green)' }}>
              {T.generatedBy(genModel)}
            </div>
          )}
          {genError && (
            <div className="text-[10px] mt-1" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-red)' }}>
              ✗ {genError}
            </div>
          )}
        </div>
        <button
          onClick={autoGenerate}
          disabled={generating}
          className="flex items-center gap-2 text-[11px] px-4 py-2 rounded-sm transition-all flex-shrink-0 ml-4"
          style={{
            fontFamily:  'IBM Plex Mono, monospace',
            background:  generating ? 'rgba(61,158,255,0.1)' : 'rgba(61,158,255,0.08)',
            color:       generating ? 'var(--c-txt-3)' : 'var(--c-blue)',
            border:      '1px solid rgba(61,158,255,0.3)',
            cursor:      generating ? 'not-allowed' : 'pointer',
            opacity:     generating ? 0.7 : 1,
          }}
        >
          {generating ? (
            <>
              <span style={{ display: 'inline-block', animation: 'spin 1s linear infinite' }}>◌</span>
              {T.generating}
            </>
          ) : T.autoGenerateBtn}
        </button>
      </div>

      <div className="px-5 pt-3 pb-1 text-[9px] tracking-[0.15em] uppercase"
        style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-3)' }}>
        {T.billableModelsHeader}
      </div>
      <table className="w-full">
        <thead>
          <tr style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
            {[T.thModel, T.thWeight].map(h => (
              <th key={h} className="px-5 py-2 text-left" style={LABEL_STYLE}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {Object.entries(weights).map(([model, w]) => (
            <tr key={model} style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
              <td className="px-5 py-2">
                <span className="text-[11px]" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-1)' }}>
                  {model}
                </span>
              </td>
              <td className="px-5 py-2">
                <span
                  className="text-[12px] font-medium"
                  style={{
                    fontFamily: 'IBM Plex Mono, monospace',
                    color: w > 50 ? 'var(--c-red)' : w > 10 ? 'var(--c-amber)' : 'var(--c-green)',
                  }}
                >
                  {w}×
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="px-5 pt-4 pb-1 text-[9px] tracking-[0.15em] uppercase"
        style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-3)', borderTop: '1px solid var(--c-border-dim)', marginTop: '4px' }}>
        {T.freeModelsHeader}
      </div>
      <table className="w-full">
        <thead>
          <tr style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
            {[T.thModel, T.thStatus].map(h => (
              <th key={h} className="px-5 py-2 text-left" style={LABEL_STYLE}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {FREE_MODELS.map(m => (
            <tr key={m.name} style={{ borderBottom: '1px solid var(--c-border-dim)', opacity: 0.7 }}>
              <td className="px-5 py-2">
                <div className="text-[11px]" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-1)' }}>
                  {m.name}
                </div>
                <div className="text-[10px] mt-0.5" style={{ color: 'var(--c-txt-3)' }}>
                  {m.provider}
                </div>
              </td>
              <td className="px-5 py-2">
                <span className="text-[9px] px-2 py-0.5 rounded-sm tracking-[0.08em] uppercase"
                  style={{
                    fontFamily: 'IBM Plex Mono, monospace',
                    color:      'var(--c-blue)',
                    background: 'rgba(61,158,255,0.08)',
                    border:     '1px solid rgba(61,158,255,0.2)',
                  }}>
                  {T.noQuotaTag}
                </span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="px-5 py-3 text-[10px]" style={{ fontFamily: 'IBM Plex Mono, monospace', color: 'var(--c-txt-3)', borderTop: '1px solid var(--c-border-dim)' }}>
        {T.weightsRedeployNote}
      </div>

      <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}

function Section({ title, subtitle, children }: {
  title: string;
  subtitle: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-md overflow-hidden" style={{ background: 'var(--c-card)', border: '1px solid var(--c-border)' }}>
      <div className="px-5 py-4" style={{ borderBottom: '1px solid var(--c-border-dim)' }}>
        <div className="text-[13px] font-semibold" style={{ fontFamily: 'Syne, sans-serif' }}>{title}</div>
        <div className="text-[11px] mt-1" style={{ color: 'var(--c-txt-3)' }}>{subtitle}</div>
      </div>
      {children}
    </div>
  );
}

function NumInput({ value, onChange, unit, width }: {
  value: number; onChange: (v: number) => void; unit: string; width: string;
}) {
  return (
    <div className="flex items-center gap-1.5">
      <input
        type="number" value={value}
        onChange={e => onChange(Number(e.target.value))}
        className={`${width} text-[11px] px-2 py-1.5 rounded-sm outline-none`}
        style={{ fontFamily: 'IBM Plex Mono, monospace', background: 'var(--c-bg)', border: '1px solid var(--c-border)', color: 'var(--c-txt-1)' }}
      />
      <span className="text-[10px]" style={{ color: 'var(--c-txt-3)', fontFamily: 'IBM Plex Mono, monospace' }}>{unit}</span>
    </div>
  );
}

function SaveBtn({ T, saving, saved, onClick }: { T: typeof T_EN; saving: boolean; saved: boolean; onClick: () => void }) {
  return (
    <button
      onClick={onClick} disabled={saving}
      className="text-[11px] px-3.5 py-1.5 rounded-sm transition-all"
      style={{
        fontFamily: 'IBM Plex Mono, monospace',
        background: saved ? 'var(--c-green)' : 'rgba(0,232,122,0.1)',
        color:      saved ? '#050a0f' : 'var(--c-green)',
        border:     '1px solid rgba(0,232,122,0.3)',
        cursor:     saving ? 'not-allowed' : 'pointer',
        opacity:    saving ? 0.6 : 1,
      }}
    >
      {saving ? T.saving : saved ? T.saved : T.save}
    </button>
  );
}
